apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: local-chart

helmGlobals:
  chartHome: ../../../../../helm-charts

helmCharts:
  - name: plants
    releaseName: plants
    valuesFile: values.yaml
    namespace: plants
    includeCRDs: false
