apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: simple-chart

helmCharts:
  - name: chart
    repo: https://seanturner026.github.io/simple-helm
    version: 0.6.0
    releaseName: simple-chart
    includeCRDs: true
    valuesFile: ../../base.yaml
    additionalValuesFiles:
      - values.yaml
