apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/seanturner026/argocd-applicationset.git
        revision: HEAD
        directories:
          # Wouldn't actually deploy a production Application in this ApplicationSet, but, want to demonstrate shared
          # values.yaml
          - path: apps/data/*/overlays/production
          - path: apps/data/*/overlays/staging
          - path: apps/infra/*/overlays/staging
        values:
          # Don't include the environment in the Application name for infra Applications as they do not deploy multiple
          # environments on the same Cluster.
          name: |-
            {{- if eq (index .path.segments 1) "infra" -}}
            {{ index .path.segments 2 }}
            {{- else -}}
            {{ index .path.segments 2 }}-{{ index .path.segments 4 }}
            {{- end -}}
          application_name: "{{ index .path.segments 2 }}"
          environment: "{{index .path.segments 4}}"

  template:
    metadata:
      name: "{{.values.name}}"
      annotations:
        notifications.argoproj.io/subscribe.on-health-degraded.slack: argocd
        notifications.argoproj.io/subscribe.on-sync-failed.slack: argocd
      labels:
        environment: "{{.values.environment}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/seanturner026/argocd-applicationset.git
        targetRevision: HEAD
        path: "{{.path.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.values.name}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
