apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-set
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/seanturner026/argocd-applicationset
    targetRevision: main
    path: clusters/staging/argocd-appset.yaml
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
