apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: data
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/seanturner026/argocd-applicationset.git
        revision: HEAD
        directories:
          - path: apps/data/*/overlays/staging
        values:
          name: "{{ index .path.segments 2 }}-{{ index .path.segments 4 }}"
          environment: "{{index .path.segments 4}}"
          images: seanturner026/kube-playground-http-server:latest
          strategy: digest

  template:
    metadata:
      name: "{{.values.name}}"
      annotations:
        notifications.argoproj.io/subscribe.on-health-degraded.slack: argocd
        notifications.argoproj.io/subscribe.on-sync-failed.slack: argocd
        argocd-image-updater.argoproj.io/image-list: "{{.values.images}}"
        argocd-image-updater.argoproj.io/update-strategy: "{{.values.strategy}}"
        argocd-image-updater.argoproj.io/write-back-method: argocd
      labels:
        environment: "{{.values.environment}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/seanturner026/argocd-applicationset.git
        targetRevision: HEAD
        path: "{{.path.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.values.name}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
