apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/seanturner026/argocd-applicationset.git
        revision: HEAD
        directories:
          - path: apps/infra/*/overlays/staging
        values:
          name: "{{ index .path.segments 2 }}"
          namespace: "{{ index .path.segments 2 }}"

  template:
    metadata:
      name: "{{ .values.name }}"
      labels:
        team: "{{ index .path.segments 1 }}"
        environment: "{{ index .path.segments 4 }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/seanturner026/argocd-applicationset.git
        targetRevision: HEAD
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .values.namespace }}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    metadata:
      annotations:
        notifications.argoproj.io/subscribe.on-health-degraded.slack: argocd
        notifications.argoproj.io/subscribe.on-sync-failed.slack: argocd
    spec:
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
