apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/seanturner026/argocd-applicationset.git
        revision: HEAD
        directories:
          - path: apps/infra/*/overlays/staging
        values:
          name: "{{ index .path.segments 2 }}"
          namespace: |
            {{- $argocd_apps := list
              "argocd-image-updater"
            -}}
            {{- if has (index .path.segments 2) $argocd_apps -}}
            argocd
            {{- else -}}
            {{ index .path.segments 2 }}
            {{- end -}}
  template:
    metadata:
      name: "{{ .values.name }}"
      labels:
        team: "{{ index .path.segments 1 }}"
        environment: "{{ index .path.segments 4 }}"
      annotations:
        notifications.argoproj.io/subscribe.on-health-degraded.slack: argocd
        notifications.argoproj.io/subscribe.on-sync-failed.slack: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/seanturner026/argocd-applicationset.git
        targetRevision: HEAD
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .values.namespace }}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true

  templatePatch: |
    {{- if eq .values.name "karpenter-crds"  }}
      spec:
        ignoreDifferences:
          - group: apiextensions.k8s.io/v1
            kind: CustomResourceDefinition
            name: ec2nodeclasses.karpenter.k8s.aws
            jsonPointers:
              - /spec/conversion/webhook/clientConfig/service/name
    {{- end }}
