# https://fabianlee.org/2022/04/18/kubernetes-kustomize-with-helm-charts/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-chart

configMapGenerator:
- name: nginx
  namespace: default
  files:
  - index.html

helmChartInflationGenerator:
- chartName: nginx
  chartRepoUrl: https://charts.bitnami.com/bitnami
  chartVersion: 15.14.0
  releaseName: nginx
  releaseNamespace: nginx
  # values: values.yaml
