# https://fabianlee.org/2022/04/18/kubernetes-kustomize-with-helm-charts/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx

configMapGenerator:
  - name: nginx
    namespace: default
    files:
      - index.html

# If multiple environments needed to be supported, do the following:
# - Specify a values.yaml in a non overlays directory
# - Utilize additionalValuesFiles to specify the environment specific values
#   - https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_helmchartinflationgenerator_
helmChartInflationGenerator:
  - chartName: nginx
    chartRepoUrl: https://charts.bitnami.com/bitnami
    chartVersion: 15.14.0
    releaseName: nginx
    releaseNamespace: nginx
    # values: values.yaml
