apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# secret.yaml is not included by design.
resources:
  - resources/configmap.yaml
  - resources/cron-job.yaml

images:
  - name: renovate/renovate
    newTag: "37.411"
