apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.12.3/manifests/install.yaml

patches:
  - path: patches/configmap.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
