apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-rollouts-staging

resources:
  - https://raw.githubusercontent.com/argoproj/argo-rollouts/v1.7.0/manifests/install.yaml
