name: Renovate PR Labeler

on:
  pull_request:
    types:
      - labeled

jobs:
  label-base-branch:
    if: contains(github.event.label.name, 'renovate')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Label PR with base branch name
        run: gh pr edit ${{ github.event.pull_request.number }} --add-label ${{ github.base_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
